version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: apavlidi/app
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME:latest
  deploy-prod:
    environment:
      IMAGE_NAME: apavlidi/app
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy Docker image
          command: |
            ssh -oStrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST "./deploy.sh $IMAGE_NAME"

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master